services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yetanothercrm
    ports:
      - "5432:5432"
    volumes:
      - yetanothercrm_pg:/var/lib/postgresql/data

volumes:
  yetanothercrm_pg:
